name: Continuous Integration

on: [push, pull_request]

env:
    MAX_LINE_LENGTH: 120
    MODULE_UNDER_TEST: "greprepos"

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.10"]
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            - name: Lint with flake8
              run: flake8 --max-line-length=${MAX_LINE_LENGTH} ${MODULE_UNDER_TEST}
            - name: Lint with pycodestyle
              run: pycodestyle --max-line-length=${MAX_LINE_LENGTH} ${MODULE_UNDER_TEST}
            - name: Lint with pylint
              run: pylint --max-line-length=${MAX_LINE_LENGTH} ${MODULE_UNDER_TEST}
            - name: Lint with black
              run: black --line-length ${MAX_LINE_LENGTH} ${MODULE_UNDER_TEST} --diff --color --check
            - name: Typecheck with mypy
              run: git ls-files '*.py' | xargs mypy
